import httpx
print('=== exchangerate.host ===')
r = httpx.get('https://api.exchangerate.host/latest', params={'base':'USD','symbols':'GBP,EUR'})
print(r.status_code)
print(r.text)
print('=== frankfurter.app ===')
r = httpx.get('https://api.frankfurter.app/latest', params={'from':'USD','to':'GBP,EUR'})
print(r.status_code)
print(r.text)
print('=== metals.live ===')
r = httpx.get('https://api.metals.live/v1/spot/gold,silver')
print(r.status_code)
print(r.text[:500])
print('=== coingecko ===')
r = httpx.get('https://api.coingecko.com/api/v3/simple/price', params={'ids':'bitcoin,ethereum,monero','vs_currencies':'usd,gbp'})
print(r.status_code)
print(r.text)
